#define METHOD_FORCING_GUO
//#define METHOD_STEPPING_AB

#define FLUID
#define FLUID_BC_WALL_Y
#define FLUID_FORCING_SPONGE
//#define FLUID_BC_WALL_YP_SLIP
//#define FLUID_BC_WALL_YM_SLIP
//#define FLUID_BC_WALL_X

//#define TEMPERATURE
//#define TEMPERATURE_BC_ISO_Y
//#define TEMPERATURE_BC_ISO_Y_BBACK
//#define TEMPERATURE_BUOYANCY
//#define TEMPERATURE_MELTING
//#define TEMPERATURE_INITIAL_PERTURBATION

//#define SALT
//#define SALT_BC_ISO_Y
//#define SALT_BC_ISO_Y_BBACK
//#define SALT_BUOYANCY
//#define SALT_INITIAL_CONSTANT
//#define SALT_INITIAL_LINEAR
