#define METHOD_FORCING_GUO

#define FLUID
#define FLUID_BC_WALL_Y
#define FLUID_BC_WALL_YP_SLIP
#define FLUID_BC_WALL_YM_SLIP
//#define FLUID_BC_WALL_X

#define TEMPERATURE
#define TEMPERATURE_BC_ISO_Y
#define TEMPERATURE_BUOYANCY
//#define TEMPERATURE_MELTING

#define SALT
#define SALT_BC_ISO_Y
#define SALT_BUOYANCY
#define SALT_INITIAL_CONSTANT
//#define SALT_INITIAL_LINEAR
